Repository Olumpusgroup/Hactoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#9 Added files for opencv Basics
  DIP/Assignment1/Assignment1.pdf
  DIP/Assignment1/Lab1.py
  DIP/Assignment1/Lenna.png
  DIP/Assignment1/calvinHobbes.jpeg
  DIP/Assignment1/chScaled.jpeg
  DIP/Assignment1/gray4Lenna.png
  DIP/Assignment1/grayLenna.png
Labels: hacktoberfest-accepted

#11 Added files for opencv pixel operations
  DIP/Assignment 2/ChessBoardGrad.png
  DIP/Assignment 2/Lenna.png
  DIP/Assignment 2/Lenna_16.png
  DIP/Assignment 2/Lenna_2.png
  DIP/Assignment 2/Lenna_32.png
  DIP/Assignment 2/Lenna_4.png
  DIP/Assignment 2/Lenna_8.png
  DIP/Assignment 2/aimg1.jpg
  DIP/Assignment 2/aimg2.jpg
  DIP/Assignment 2/aimg3_cv2_add.jpg
  DIP/Assignment 2/aimg3_cv2_addWeighted.jpg
  DIP/Assignment 2/aimg3_pixel_by_pixel.jpg
  DIP/Assignment 2/mask.jpg
  DIP/Assignment 2/shading.png
  DIP/Assignment 2/simg1.png
  DIP/Assignment 2/simg2.png
  DIP/Assignment 2/simg3_subtract.jpg
  DIP/Assignment 2/simg3_thresholding.jpg
  DIP/Assignment 2/teeth.jpg
  DIP/Assignment 2/u4cse20312-assignment2.py
Labels: hacktoberfest-accepted

#14 Hacker
  Nirmal/Hacker.cpp
Labels: hacktoberfest-accepted

#15 Kalaash Nikavoo KGF.cpp
  Nirmal/KGF.cpp
Labels: hacktoberfest-accepted

#16 PawriQuestonCompleted
  Codechef/PawriREADME.md
  Codechef/pawri.cpp
  Codechef/pawri.exe
Labels: hacktoberfest-accepted

#17 Adds 231A, 331C1, 469A, 1195C, 1408F, 1461D Codeforces problem solutions
  Codeforces/1195C.cpp
  Codeforces/1408F.cpp
  Codeforces/1461D.cpp
  Codeforces/231A.cpp
  Codeforces/331C1.cpp
  Codeforces/469A.cpp
  Codeforces/README.md
Labels: hacktoberfest-accepted

#18 chef and Wildcard
  Codechef/chef&WildCard.md
  Codechef/chefandwildcard.cpp
  Codechef/chefandwildcard.exe
Labels: hacktoberfest-accepted

#21 Added questions in the codechef folder
  Codechef/Ezio and Guards/Ezi and Guards.md
  Codechef/Ezio and Guards/solution.cpp
Labels: hacktoberfest-accepted

#23 Magical Door
  Codechef/magicaldoor.cpp
  Codechef/magicaldoor.exe
  Codechef/magicaldoor.md
Labels: hacktoberfest-accepted

#24 Adds new algorithms
  Algorithms/arrayNearestInt.cpp
  Algorithms/mergeSort.cpp
Labels: hacktoberfest-accepted

#25 pull
  Abhay/BoxIt.cpp
Labels: hacktoberfest-accepted

#26 basics and most common algo used in ml with dataset and readme file.
  ML/InterLevel DecisionTreeAlgo/Iris.csv
  ML/InterLevel DecisionTreeAlgo/IrisTree.png
  ML/InterLevel DecisionTreeAlgo/LGM Task (2).ipynb
  ML/README.md
  ML/begginer irisflower classification/iris.ipynb
  ML/begginer irisflower classification/task1.py
Labels: hacktoberfest-accepted

#29 codecheff qs
  Codechef/Queries in an Array ans.cpp
  Codechef/Queries in an Array.md
Labels: hacktoberfest-accepted, hactoberfest

#31 decision_tree_salary_classification
  ML-Mini-Projects/README.md
  ML-Mini-Projects/decision_tree_salary_classification.ipynb
Labels: hacktoberfest-accepted, hactoberfest

#32 titanic_survival_classification
  ML-Mini-Projects/titanic_survival_classification.ipynb
Labels: hacktoberfest-accepted, hactoberfest

#33 salary_prediction_linear_regression
  ML-Mini-Projects/simple_linear_regression.ipynb
Labels: hacktoberfest-accepted, hactoberfest

#34 data_structures_qns
  ML-Mini-Projects/DS/buildArrayFromPermutation.cpp
  ML-Mini-Projects/DS/buildArrayFromPermutation.py
Labels: hacktoberfest-accepted, hactoberfest

#35 data_structures_string_qns
  ML-Mini-Projects/DS/reverseStringII.py
Labels: hacktoberfest-accepted, hactoberfest

#36 updated the README.md
  README.md
Labels: hacktoberfest-accepted, hactoberfest

#38 Added KMP Algorithm
  Algorithms/KMP Algorithm.cpp
  Algorithms/Z Algorithm.cpp
Labels: hacktoberfest-accepted, hactoberfest

#39 Added Chef_and_Magical_Steps ( CodeChef )
  Codechef/Chef_and_Magical_Steps.cpp
Labels: hacktoberfest-accepted, hactoberfest

#40 integer to words.java
  Codechef/integer to words.java
Labels: hacktoberfest-accepted, hactoberfest

#42 immobileknight
  Codechef/immobleKnight.cpp
  Codechef/immoblieKnight.md
Labels: hacktoberfest-accepted, hactoberfest

#43 Added C Program
  C Programs/area.c
  C Programs/big.c
  C Programs/ggg.c
  C Programs/hft.c
  C Programs/hgv.c
  C Programs/swap.c
Labels: hacktoberfest-accepted, hactoberfest

#45 JAVA PROBLEMS
  Codechef/Cqueue.java
  Codechef/Driver.java
  Codechef/Queue.java
Labels: hacktoberfest-accepted, hactoberfest

#46 Added C++ Programs
  C++ Programs/fibo.cpp
  C++ Programs/linearSearch.cpp
  C++ Programs/multiplicationtable.cpp
  C++ Programs/pattern12.cpp
  C++ Programs/prime.cpp
  C++ Programs/pthagoreantriangle.cpp
  C++ Programs/reversenumber.cpp
Labels: hacktoberfest-accepted, hactoberfest

#51 Create Banking management system.c
  C Programs/Banking management system.c
Labels: hacktoberfest-accepted, hactoberfest

#52 Added a C program to reverse a number
  C Programs/reverse-number-program.c
Labels: hacktoberfest-accepted, hactoberfest

#53 Create Numerical_IterationMethods.py
  Python Programs/Numerical_IterationMethods.py
Labels: hacktoberfest-accepted, hactoberfest

#56 Added leetcode problem-ceiling of a number
  Alan/ceilingofnumber.java
Labels: hacktoberfest-accepted, hactoberfest

#67 Problem Solving solutions using Javascript
  ksaravindakashyap/RegexValidate.js
  ksaravindakashyap/SumOfNumbers.js
  ksaravindakashyap/VasyaClerk.js
  ksaravindakashyap/longestPalindrome.js
  ksaravindakashyap/persistent.js
  ksaravindakashyap/reverse.js
  ksaravindakashyap/shortestWord.js
  ksaravindakashyap/squareDigit.js
  ksaravindakashyap/sumofpairs.js
  ksaravindakashyap/testing.js
  ksaravindakashyap/tower.js
  ksaravindakashyap/tribonacci.js
  ksaravindakashyap/twoSum.js
Labels: hacktoberfest-accepted, hactoberfest

#66 Create EqualStrings.cpp
  Codechef/EqualStrings.cpp
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#65 Create GrittyGrid.cpp
  Codechef/GrittyGrid.cpp
Labels: hacktoberfest-accepted, hactoberfest

#64 Who dares to be a millionaire Codechef Solution
  Codechef/ConfusingConcatenations.py
  Codechef/WDTBAM.py
  Codechef/WDTBAM.py(1)
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#62 python programs added
  symbolic_programming.py
Labels: hacktoberfest-accepted, hactoberfest

#61 feat(Python Programs): add 'Download file'
  download_file.py
Labels: hacktoberfest-accepted, hactoberfest

#60 adding some codchef question
  Codechef/BINBASEBASIC.java
  Codechef/EUREKA.java
  Codechef/INOI1601.java
  Codechef/RISK.java
  Codechef/SNSOCIAL.java
  Codechef/SUM_INFINITE.java
  Codechef/landandwater.java
  Codechef/makediv3.java
  Codechef/number.java
  Codechef/partition_array_pivot.java
  Codechef/train.java
Labels: hacktoberfest-accepted, hactoberfest

#59 feat(Python Programs): add List in File
  Python Programs/list_in_file.py
Labels: hacktoberfest-accepted, hactoberfest

#58 feat(Python Programs): add CSV utils
  Python Programs/csv_utils.py
Labels: hacktoberfest-accepted, hactoberfest

#57 feat(Python Programs): add YAML utils
  Python Programs/yaml_utils.py
Labels: hacktoberfest-accepted, hactoberfest

#79 Create fractional_knapsack.c
  C Programs/fractional_knapsack.c
Labels: hacktoberfest-accepted, hactoberfest

#78 Create trapwater.java
  trapwater.java
Labels: hacktoberfest-accepted, hactoberfest

#76 Added python Basics programs
  Python Basics.html
Labels: hacktoberfest-accepted, hactoberfest

#75 Add Html Code
  HTML/form.html
Labels: hacktoberfest-accepted, hactoberfest

#80 Added Binary Search Algorithm
  C++ Programs/binary_search.cpp
Labels: hacktoberfest-accepted, hactoberfest
